version: '3.9'
services:
  postgres:
      image: postgres
      restart: always
      environment:
          POSTGRES_DB: todolist
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      ports:
          - '5432:5432'
      volumes:
          - ../pg_data:/var/lib/postgresql/data